### ISSUE TITLE
Replace `perseus_integration` glue crate

### ISSUE THREAD

**Issue by ghost** [framesurge/perseus#212]
Following the doc on [framesuege](https://framesurge.sh/perseus/en-US/docs/0.4.x/getting-started/first-app), the compiler said:
#[perseus::main(perseus_integration::dflt_server)]
  |                 ^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `perseus_integration`

**Comment by danielnehrig** [comment]
https://github.com/framesurge/perseus/blob/main/examples/.base/src/main.rs

**Comment by danielnehrig** [comment]
> Following the doc on [framesuege](https://framesurge.sh/perseus/en-US/docs/0.4.x/getting-started/first-app), the compiler said: #[perseus::main(perseus_integration::dflt_server)] | ^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `perseus_integration`

i don't wanna be that guy but "following the doc on ..." i mean if you'd followed it or even partially read that section you'd know about the various server integrations with warp, axum, and actix
i agree though the example in the docs could be more straight forward

**Comment by arctic-hen7** [comment]
Yeah sorry about this, I'm realizing that this is starting to be a real pain point. That crate is basically a glue crate which is very difficult to avoid. I have some time over the next week, so I'll take a look at alternate ways of doing this so we can try to get rid of this.

Since your original question has been resolved, I'm going to commandeer this issue for tracking the move to a new testing setup that doesn't involve the glue crate.

**Comment by arctic-hen7** [comment]
@danielnehrig I'll also just mention that, while your comment has some merit, it's worth considering that, while it may not be true in this case (though I have no idea), English isn't everyone's first language, and code examples should be as complete as possible (that one's completely on me). If there's one thing I've learned with writing Perseus' docs, it's that *a lot* of people rely purely on the code examples, either for speed of reading, or because they don't understand the attached prose. I'm not invalidating what you've said by any means, but I think it would be good to keep this in mind so that the Perseus community can be as welcoming as possible for people from all walks of life. 👍

**Comment by danielnehrig** [comment]
true sorry could have been more nice here certainly

**Comment by arctic-hen7** [comment]
Alright, I've 'fixed' this by aliasing `perseus-integration` to `perseus-warp` in every example's `Cargo.toml`, which makes the Rust code make perfect sense by making the `Cargo.toml` files a little more nonsensical. However, I've included the 'correct' line commented out in every one of those, along with an explanatory warning. Additionally, the examples on the website use dummy `Cargo.toml` files, which means someone following the tutorials on there shouldn't ever run up against this issue!

**Comment by auts2022** [comment]
The doc seems incomplete, e.g., [architecture](https://github.com/framesurge/perseus/blob/main/docs/0.4.x/en-US/reference/architecture.md)

**Comment by arctic-hen7** [comment]
@auts2022 yes, the docs for v0.4.x are very much a work in progress. That shouldn't have anything to do with this issue though...

**Comment by auts2022** [comment]
What's the different between [examples/website](https://github.com/framesurge/perseus/tree/main/examples/website) and [website](https://github.com/framesurge/perseus/tree/main/website) ?

**Comment by arctic-hen7** [comment]
@auts2022 this is not the place for generic discussion, please open a new discussion separately.

In answer to your question, `website` contains the code for the website, while `examples/website` is the reference for the examples used on the landing page of the website.
