### ISSUE TITLE
Missing </body></html>

### ISSUE THREAD

**Issue by Gisleburt** [framesurge/perseus#304]
This issue is reporting a bug in the code of Perseus. Details of the scope will be available in issue labels.
The author described their issue as follows:
> Missing </body></html>

The steps to reproduce this issue are as follows:
> Follow the quick start guide and serve the application, you need to "View Source" rather than Inspect as most browsers will add the mossing closing tags.

I'm brand new to Perseus (and loving it btw) so I might have missed something obvious. Happy to look at fixing it, but wanted to confirm that it actually was an issue first.

A minimum reproducible example is available at <>.
- Hydration-related: false
- The author is willing to attempt a fix: false 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWJ1Zw==

</details>

**Comment by arctic-hen7** [comment]
Ah yes, you'll probably find a lot of missing closing tags by default, as Perseus applies a highly aggressive minifier that strips many of them. Semantically, this ends up being fine, as browsers can interpret the HTML the same, but you can disable the `minify` feature if you'd like, or if you're having any problems with this.

I might close this for now, as it's expected behaviour, although I'd be very willing to accept a PR that adds some notice for this in the docs somewhere if you'd like to write that?
