### ISSUE TITLE
Installation of `wasm-opt` fails

### ISSUE THREAD

**Issue by shivshankardayal** [framesurge/perseus#329]
This issue is reporting a bug in the code of Perseus. Details of the scope will be available in issue labels.
The author described their issue as follows:
> `perseus serve -w` fails with `wasm-opt` installtion.

The steps to reproduce this issue are as follows:
>
```[shiv@DESKTOP-IBRE2O2 wasm_frontend]$ perseus serve -w
  📥 Installing external tools...❌
Error: couldn't extract 'wasm-opt' (do you have the necessary permissions?)

Caused by:
        failed to iterate over archive
        Caused by:
                unexpected end of file
```

is the output when I try to run `perseus serve -w`

A minimum reproducible example is available at <Use the quickstart example.>.
- Hydration-related: false
- The author is willing to attempt a fix: false 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWJ1ZyxBLWNsaQ==

</details>

**Comment by arctic-hen7** [comment]
Hmm, this looks like something that might arise if your internet connection suddenly dropped out? Has this happened more than once?

**Comment by shivshankardayal** [comment]
Yes, it is repeating. I would have tried like 20 times but it never works.

**Comment by arctic-hen7** [comment]
Looks like the latest version of `wasm-opt` has been incorrectly packaged and the GitHub API doesn't know its version. Working on a fix now. In the meantime, use `perseus --wasm-opt-version version_118 <rest-of-command>`. You should only need to do this once, after that it should be cached, though if the problem comes up again try that.

**Comment by arctic-hen7** [comment]
Fixed this in the latest commit, will wait for tests to pass and then cut a new release ASAP, thanks for opening an issue on this! (Very easy to miss these: Actions caching means tool installations only get tested sometimes I think, and otherwise they stay cached, so only new users spot these!)

For reference: fix was to use `tag_name` in GitHub's releases API rather than `name` (which apparently doesn't get set sometimes).
